### ISSUE TITLE
it's not working

### ISSUE THREAD

**Issue by Gh0stLee** [cwilso/Audio-Input-Effects#22]

**Comment by rowild** [comment]
What is not working?

**Comment by Gh0stLee** [comment]
the website. it says my mic is connected but it just isnt adding effects
![Screenshot 2021-07-27 034316](https://user-images.githubusercontent.com/71680099/127115929-40d7eba9-aba0-4376-a946-c165bbc96e5b.png)

**Comment by rowild** [comment]
I can assure you that the website is working fine in my case. – Why is your screenshot grey? In my case all UI elements are blue, even when the mic is deactivated (blocked). You should also see some kind of (colorful) waveform.
 
Which OS are you using? Do you have more then one audio input source (e.g. a webcam, a headset, an external microphone)? If so, are the audio settings setup properly in the OS? 
When using a mic, loudspeakers can be a problem, which is, why people usually turn them down or off (and use earphones instead). Sometimes it happens, that the process of turning down / of the loudspeakers also turns off the mic...

Also, maybe you want to check the mic settings again, which you can access via the lock symbol on the left of the browser's address bar (see screenshot, which is in German only, sorry!).

![Bildschirmfoto 2021-07-27 um 10 26 52](https://user-images.githubusercontent.com/213803/127122792-1c1c28df-de78-431b-b0f5-9f39371cab7b.png)

**Comment by Gh0stLee** [comment]
it seems to be working now but I literally didn't do anything

i had checked everything, i only have 1 mic (usb) and it says it's detected, it just wasn't working
my mic was allowed on the website (I even tried clearing the cache n restarting my browser)
the only headset I have is connected to my usb mic (I have a fifine k683)
i tried unplugging n replugging everything in
literally nothing worked

but for some reason, after literally doing nothing different, it's working today
